<?php

namespace Database\Seeders;

use App\Models\Doctor;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $doctorsData = [
            [
                "name" => "Dr. Budi Santoso",
                "email"=> "budi@gmail.com",
                "username" => "budi_santoso",
                "password" => bcrypt("asd"),
                "spesialisasi" => "umum",
                "status" => "1",
                "no_str" => "123126",
                "no_hp" => "081237010266",
                "jenis_kelamin" => "L",
                "tanggal_lahir" => "1985-05-15",
                "alamat" => "Jl. Cipto Mangunkusumo",
                "image" => "/uploads/img/doctor-1.jpg",
            ],
            [
                "name" => "Dr. Dian Permata",
                "email"=> "dian@gmail.com",
                "username" => "dian_permata",
                "password" => bcrypt("asd"),
                "spesialisasi" => "mata",
                "status" => "1",
                "no_str" => "123127",
                "no_hp" => "081237010277",
                "jenis_kelamin" => "L",
                "tanggal_lahir" => "1982-08-20",
                "alamat" => "Jl. Diponegoro",
                "image" => "/uploads/img/doctor-2.jpg",
            ],
            [
                "name" => "Dr. Eka Wijaya",
                "email"=> "eka@gmail.com",
                "username" => "eka_wijaya",
                "password" => bcrypt("asd"),
                "spesialisasi" => "gigi",
                "status" => "1",
                "no_str" => "123128",
                "no_hp" => "081237010288",
                "jenis_kelamin" => "P",
                "tanggal_lahir" => "1980-03-10",
                "alamat" => "Jl. Kusuma Negara",
                "image" => "/uploads/img/doctor-3.jpg",
            ],
            // ... (tambahkan 7 data lainnya)
            [
                "name" => "Dr. Fika Maulana",
                "email"=> "fika@gmail.com",
                "username" => "fika_maulana",
                "password" => bcrypt("asd"),
                "spesialisasi" => "umum",
                "status" => "1",
                "no_str" => "123136",
                "no_hp" => "081237010366",
                "jenis_kelamin" => "P",
                "tanggal_lahir" => "1987-11-25",
                "alamat" => "Jl. Merdeka",
                "image" => "/uploads/img/doctor-4.jpg",
            ],
            [
                "name" => "Dr. Gita Pratama",
                "email"=> "gita@gmail.com",
                "username" => "gita_pratama",
                "password" => bcrypt("asd"),
                "spesialisasi" => "mata",
                "status" => "1",
                "no_str" => "123137",
                "no_hp" => "081237010377",
                "jenis_kelamin" => "L",
                "tanggal_lahir" => "1983-09-18",
                "alamat" => "Jl. Hasanuddin",
                "image" => "/uploads/img/doctor-5.jpg",
            ],
            [
                "name" => "Dr. Hana Susanti",
                "email"=> "hana@gmail.com",
                "username" => "hana_susanti",
                "password" => bcrypt("asd"),
                "spesialisasi" => "gigi",
                "status" => "1",
                "no_str" => "123138",
                "no_hp" => "081237010388",
                "jenis_kelamin" => "P",
                "tanggal_lahir" => "1984-04-05",
                "alamat" => "Jl. Pahlawan",
                "image" => "/uploads/img/doctor-6.jpg",
            ],
            [
                "name" => "Dr. Irfan Widodo",
                "email"=> "irfan@gmail.com",
                "username" => "irfan_widodo",
                "password" => bcrypt("asd"),
                "spesialisasi" => "umum",
                "status" => "1",
                "no_str" => "123139",
                "no_hp" => "081237010399",
                "jenis_kelamin" => "L",
                "tanggal_lahir" => "1981-06-30",
                "alamat" => "Jl. Sudirman",
                "image" => "/uploads/img/doctor-7.jpg",
            ],
            [
                "name" => "Dr. Joko Santoso",
                "email"=> "joko@gmail.com",
                "username" => "joko_santoso",
                "password" => bcrypt("asd"),
                "spesialisasi" => "mata",
                "status" => "1",
                "no_str" => "123140",
                "no_hp" => "081237010400",
                "jenis_kelamin" => "L",
                "tanggal_lahir" => "1986-12-15",
                "alamat" => "Jl. Tambak Boyo",
                "image" => "/uploads/img/doctor-8.jpg",
            ],
            [
                "name" => "Dr. Kiki Nurul",
                "email"=> "kiki@gmail.com",
                "username" => "kiki_nurul",
                "password" => bcrypt("asd"),
                "spesialisasi" => "gigi",
                "status" => "1",
                "no_str" => "123141",
                "no_hp" => "081237010411",
                "jenis_kelamin" => "P",
                "tanggal_lahir" => "1988-03-20",
                "alamat" => "Jl. Pemuda",
                "image" => "/uploads/img/doctor-9.jpg",
            ],
            [
                "name" => "Dr. Lina Anggraeni",
                "email"=> "lina@gmail.com",
                "username" => "lina_anggraeni",
                "password" => bcrypt("asd"),
                "spesialisasi" => "umum",
                "status" => "1",
                "no_str" => "123142",
                "no_hp" => "081237010422",
                "jenis_kelamin" => "P",
                "tanggal_lahir" => "1989-08-10",
                "alamat" => "Jl. Kartini",
                "image" => "/uploads/img/doctor-10.jpg",
            ],
            [
                "name" => "Dr. Mira Susanti",
                "email"=> "mira@gmail.com",
                "username" => "mira_susanti",
                "password" => bcrypt("asd"),
                "spesialisasi" => "umum",
                "status" => "1",
                "no_str" => "123143",
                "no_hp" => "081237010433",
                "jenis_kelamin" => "P",
                "tanggal_lahir" => "1990-02-25",
                "alamat" => "Jl. Veteran",
                "image" => "/uploads/img/mira.jpg",
            ],
            [
                "name" => "Dr. Nanda Putra",
                "email"=> "nanda@gmail.com",
                "username" => "nanda_putra",
                "password" => bcrypt("asd"),
                "spesialisasi" => "mata",
                "status" => "1",
                "no_str" => "123144",
                "no_hp" => "081237010444",
                "jenis_kelamin" => "L",
                "tanggal_lahir" => "1991-07-10",
                "alamat" => "Jl. Kalimantan",
                "image" => "/uploads/img/nanda.jpg",
            ],
            [
                "name" => "Dr. Oki Rahayu",
                "email"=> "oki@gmail.com",
                "username" => "oki_rahayu",
                "password" => bcrypt("asd"),
                "spesialisasi" => "gigi",
                "status" => "1",
                "no_str" => "123145",
                "no_hp" => "081237010455",
                "jenis_kelamin" => "P",
                "tanggal_lahir" => "1992-12-05",
                "alamat" => "Jl. Dipati Ukur",
                "image" => "/uploads/img/oki.jpg",
            ],
            [
                "name" => "Dr. Purnama Setiawan",
                "email"=> "purnama@gmail.com",
                "username" => "purnama_setiawan",
                "password" => bcrypt("asd"),
                "spesialisasi" => "umum",
                "status" => "1",
                "no_str" => "123146",
                "no_hp" => "081237010466",
                "jenis_kelamin" => "L",
                "tanggal_lahir" => "1993-05-20",
                "alamat" => "Jl. Hayam Wuruk",
                "image" => "/uploads/img/purnama.jpg",
            ],
            [
                "name" => "Dr. Qori Anwar",
                "email"=> "qori@gmail.com",
                "username" => "qori_anwar",
                "password" => bcrypt("asd"),
                "spesialisasi" => "mata",
                "status" => "1",
                "no_str" => "123147",
                "no_hp" => "081237010477",
                "jenis_kelamin" => "L",
                "tanggal_lahir" => "1994-10-15",
                "alamat" => "Jl. Pahlawan Revolusi",
                "image" => "/uploads/img/qori.jpg",
            ],
            [
                "name" => "Dr. Rini Kusuma",
                "email"=> "rini@gmail.com",
                "username" => "rini_kusuma",
                "password" => bcrypt("asd"),
                "spesialisasi" => "gigi",
                "status" => "1",
                "no_str" => "123148",
                "no_hp" => "081237010488",
                "jenis_kelamin" => "P",
                "tanggal_lahir" => "1995-03-30",
                "alamat" => "Jl. Gatot Subroto",
                "image" => "/uploads/img/rini.jpg",
            ],
            [
                "name" => "Dr. Satria Wibowo",
                "email"=> "satria@gmail.com",
                "username" => "satria_wibowo",
                "password" => bcrypt("asd"),
                "spesialisasi" => "umum",
                "status" => "1",
                "no_str" => "123149",
                "no_hp" => "081237010499",
                "jenis_kelamin" => "L",
                "tanggal_lahir" => "1996-08-25",
                "alamat" => "Jl. Sudirman",
                "image" => "/uploads/img/satria.jpg",
            ],
            [
                "name" => "Dr. Tiara Putri",
                "email"=> "tiara@gmail.com",
                "username" => "tiara_putri",
                "password" => bcrypt("asd"),
                "spesialisasi" => "mata",
                "status" => "1",
                "no_str" => "123150",
                "no_hp" => "081237010500",
                "jenis_kelamin" => "P",
                "tanggal_lahir" => "1997-01-10",
                "alamat" => "Jl. Jakarta",
                "image" => "/uploads/img/tiara.jpg",
            ],
            [
                "name" => "Dr. Umar Abdullah",
                "email"=> "umar@gmail.com",
                "username" => "umar_abdullah",
                "password" => bcrypt("asd"),
                "spesialisasi" => "gigi",
                "status" => "1",
                "no_str" => "123151",
                "no_hp" => "081237010511",
                "jenis_kelamin" => "L",
                "tanggal_lahir" => "1998-06-15",
                "alamat" => "Jl. Diponegoro",
                "image" => "/uploads/img/umar.jpg",
            ],
            [
                "name" => "Dr. Vina Rosita",
                "email"=> "vina@gmail.com",
                "username" => "vina_rosita",
                "password" => bcrypt("asd"),
                "spesialisasi" => "umum",
                "status" => "1",
                "no_str" => "123152",
                "no_hp" => "081237010522",
                "jenis_kelamin" => "P",
                "tanggal_lahir" => "1999-11-20",
                "alamat" => "Jl. Pajajaran",
                "image" => "/uploads/img/vina.jpg",
            ],
        ];

        
        foreach ($doctorsData as $data) {
            Doctor::create([
                "name" => $data["name"],
                "email" => $data["email"],
                "username" => $data["username"],
                "password" => $data["password"],
                "spesialisasi" => $data["spesialisasi"],
                "status" => $data["status"],
                "no_str" => $data["no_str"],
                "no_hp" => $data["no_hp"],
                "jenis_kelamin" => $data["jenis_kelamin"],
                "tanggal_lahir" => $data["tanggal_lahir"],
                "alamat" => $data["alamat"],
                "image" => $data["image"],
            ]);
        }
    }
}
